# Github Actions para automatizar el deploy a railway
name: Deploy to Railway

# triggers: cuando se ejcuta el workflow
on:
  push:
    branches: 
      - main # se ejecuta cuando se hace push a main

jobs:
  deploy:
    # SO para ejecutar el job (por default)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g @railway/cli # instala railwaycli
      - run: railway up --service=estelar-code
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} # token para que interactúe con railway